/**
 * Central registry of REST API endpoints.
 * All paths are relative to NEXT_PUBLIC_API_URL.
 */
export const ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    refresh: "/auth/refresh-token",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/auth/verify-email",
    changePassword: "/auth/change-password",
    me: "/auth/me",
    profile: "/auth/profile",
    avatar: "/auth/avatar",
  },
  dashboard: {
    stats: "/dashboard/stats",
    salesChart: "/dashboard/sales-chart",
    funnel: "/dashboard/funnel",
    pipeline: "/dashboard/pipeline",
    activities: "/dashboard/recent-activities",
    tasks: "/dashboard/upcoming-tasks",
  },
  customers: "/customers",
  contacts: "/contacts",
  leads: "/leads",
  opportunities: "/opportunities",
  deals: "/deals",
  products: "/products",
  productCategories: "/product-categories",
  quotes: "/quotes",
  orders: "/orders",
  invoices: "/invoices",
  payments: "/payments",
  tasks: "/tasks",
  activities: "/activities",
  events: "/events",
  campaigns: "/campaigns",
  tickets: "/tickets",
  notifications: "/notifications",
  reports: "/reports",
  users: "/users",
  roles: "/roles",
  permissions: "/permissions",
  files: "/files",
  search: "/search",
  settings: {
    company: "/settings/company",
    branches: "/settings/branches",
    departments: "/settings/departments",
    teams: "/settings/teams",
    email: "/settings/email",
    sms: "/settings/sms",
    tax: "/settings/tax",
    currency: "/settings/currency",
    preferences: "/settings/preferences",
  },
};
